("html" ()
  ("head" ())
  ("body" ()
   ("img" (("src" . "http://www.uoguelph.ca/common/zimbra/AppBanner.png")
           ("alt" . "Gryph Mail and Calendar")))
   ("form" (("action" . "") ("method" . "GET") ("class" . "login"))
    ("input" (("type" . "hidden") ("name" . "r") ("value" . "*redir*")))
    ("input" (("type" . "hidden") ("name" . "q") ("value" . "*query*")))
    ("table" ()
     ("tr" ()
      ("th" (("colspan" . "2")) "Sign In"))
     ("tr" ()
      ("td" ()
       ("table" (("class" . "nested"))
        ("tr" ()
         ("td" (("colspan" . "2"))))
        ("tr" ()
         ("td" (("align" . "right"))
          ("label" (("for" . "n")) "Name:"))
         ("td" ()
          ("input" (("name" . "n") ("value" . "")))))
        ("tr" ()
         ("td" (("align" . "right"))
          ("label" (("for" . "u")) "Password:"))
         ("td" ()
          ("input" (("name" . "p") ("type" . "password") ("value" . "")))))
        ("tr" ()
         ("td" (("colspan" . "2") ("align" . "center"))
          ("input" (("name" . "a") ("type" . "submit") ("value" . "OK"))))))))))
   ("h1" () "Gryph Mail Tweaks")
   ("hr" () "*cgi-path-info*")))
